import { CARRYOVER } from "../data/portfolio";

export default function CarryoverPage(){return <article className="case-study carryover-case">
  <header className="case-hero section-shell"><div className="case-kicker"><span>Selected work / 02</span><span>Independent product case study / 2026</span></div><p className="eyebrow">Carryover · Plant continuity</p><h1>Shift continuity for the work that cannot be dropped.</h1><p>{CARRYOVER.problem}</p><div className="button-row"><a className="button button-primary" href={CARRYOVER.repoUrl} target="_blank" rel="noreferrer">View source ↗</a><a className="text-link" href={CARRYOVER.repoUrl} target="_blank" rel="noreferrer">Open repository ↗</a></div></header>
  <section className="case-snapshot section-shell" aria-label="Project snapshot"><div><span>Role</span><strong>{CARRYOVER.responsibilities.join(" · ")}</strong></div><div><span>Stack</span><strong>{CARRYOVER.technologies.join(" · ")}</strong></div><div><span>Boundary</span><strong>Fictional industrial records; local demonstration permissions; replaceable data adapter</strong></div></section>
  <section className="section-shell carryover-journey"><p className="eyebrow">Signature journey</p><h2>One observation becomes an accountable operating record.</h2><ol><li><span>01</span>Observation</li><li><span>02</span>Carryover decision</li><li><span>03</span>Incoming acknowledgement</li><li><span>04</span>Assigned action</li><li><span>05</span>Resolution evidence</li><li><span>06</span>Updated record</li></ol></section>
  <section className="section-shell carryover-screen"><img src="/projects/carryover-overview.png" alt="Carryover overview showing current shift pressure and incoming priority" width="1440" height="900"/><div><p className="eyebrow">Overview</p><h2>Operating pressure before dashboard decoration.</h2><p>The current shift sees what remains unresolved, which condition is most important, who owns it, and what decision the incoming team must protect.</p></div></section>
  <section className="section-shell evidence-section"><header className="section-heading"><p className="eyebrow">Product evidence</p><h2>Every workspace supports the same continuity path.</h2></header><div className="evidence-grid">{CARRYOVER.evidence.map(item=><article key={item.label}><strong>{item.value}</strong><span>{item.label}</span><p>{item.detail}</p></article>)}</div><p className="evidence-note">Verification: 13 domain and export tests and the production TypeScript/Vite build passed on August 13, 2026.</p></section>
  <section className="section-shell screen-study"><header className="section-heading split-heading"><div><p className="eyebrow">Responsive workflow</p><h2>Comparison on desktop. Action order on mobile.</h2></div><p>Issue tables become direct, full-width operating records without losing severity, state, ownership, or evidence.</p></header><div className="screen-pair"><figure><img src="/projects/carryover-issues.png" alt="Carryover desktop issue register" width="1440" height="900"/><figcaption><strong>Complete issue register</strong><span>Search and filter across equipment, area, severity, state, and owner.</span></figcaption></figure><figure className="mobile-screen"><img src="/projects/carryover-mobile.png" alt="Carryover issue detail on mobile" width="390" height="844"/><figcaption><strong>Mobile operating record</strong><span>Observation, decision, evidence, and audit in direct sequence.</span></figcaption></figure></div></section>
  <section className="section-shell decision-section"><header className="section-heading"><p className="eyebrow">Selected decisions</p><h2>Industrial credibility comes from boundaries and state.</h2></header><div className="decision-grid">{CARRYOVER.decisions.map((decision,index)=><article key={decision.title}><span>0{index+1}</span><h3>{decision.title}</h3><p>{decision.body}</p></article>)}</div></section>
  <section className="section-shell reflection-section"><div><p className="eyebrow">Reflection</p><h2>What a real plant deployment would require.</h2></div><div><p>{CARRYOVER.reflection}</p><p className="disclosure">{CARRYOVER.disclosure}</p></div></section>
</article>}
