import { CARRYOVER } from "../data/portfolio";
import LiveProjectPreview from "../components/LiveProjectPreview";

const workflow = ["Observation", "Prepared handoff", "Incoming cross-check", "Assigned action", "Resolution evidence", "Updated record"] as const;

export default function CarryoverPage() {
  return <article className="case-study carryover-case">
    <header className="case-hero section-shell"><div className="case-kicker"><span>Selected work / 02</span><span>Independent product / {CARRYOVER.year}</span></div><h1>Carryover makes responsibility visible when the shift changes.</h1><p>{CARRYOVER.problem}</p><div className="button-row"><a className="button button-primary" href={`${CARRYOVER.liveUrl}/?tour=handoff`} target="_blank" rel="noreferrer">Run the handoff ↗</a><a className="button button-secondary" href={CARRYOVER.liveUrl} target="_blank" rel="noreferrer">Open product ↗</a><a className="text-link" href={CARRYOVER.repoUrl} target="_blank" rel="noreferrer">View source ↗</a></div></header>
    <section className="case-snapshot section-shell" aria-label="Project snapshot"><div><span>Role</span><strong>{CARRYOVER.responsibilities.join(" · ")}</strong></div><div><span>Stack</span><strong>{CARRYOVER.technologies.join(" · ")}</strong></div><div><span>Boundary</span><strong>Fictional client-side product; not a replacement for approved plant procedures</strong></div></section>
    <section className="section-shell case-problem" aria-labelledby="carryover-problem"><div><p className="eyebrow">The product problem</p><h2 id="carryover-problem">An unresolved condition needs more than a note.</h2></div><div className="long-copy"><p>A broadcast says what happened. A handoff establishes who verified the current state, who now owns the work, what proof is expected, and what must be true before the record closes.</p><p>Carryover turns that responsibility chain into the product’s information architecture instead of hiding it behind dashboard totals.</p></div></section>
    <section className="section-shell system-section" aria-labelledby="carryover-workflow"><header className="section-heading"><p className="eyebrow">Signature workflow</p><h2 id="carryover-workflow">The record advances only when the work does.</h2></header><ol className="carryover-workflow">{workflow.map((step, index) => <li key={step}><span>0{index + 1}</span><strong>{step}</strong></li>)}</ol></section>
    <section className="section-shell carryover-live" aria-labelledby="carryover-live-title"><header className="section-heading split-heading"><div><p className="eyebrow">Live product evidence</p><h2 id="carryover-live-title">Inspect the operating brief at working scale.</h2></div><p>The embedded window is the deployed product. Selecting it opens Carryover in a new tab; the guided URL then uses the actual forms, permissions, persistence, and audit trail.</p></header><LiveProjectPreview href={CARRYOVER.liveUrl} label="Carryover shift continuity product" pathLabel="carryover-6m1z.vercel.app" posterSrc="/projects/carryover-overview.png" previewHeight={900} /></section>
    <section className="section-shell evidence-section" aria-labelledby="carryover-evidence"><header className="section-heading"><p className="eyebrow">Verified evidence</p><h2 id="carryover-evidence">The release standard is part of the product.</h2></header><div className="evidence-grid">{CARRYOVER.evidence.map((item) => <article key={item.label}><strong>{item.value}</strong><span>{item.label}</span><p>{item.detail}</p></article>)}</div><p className="evidence-note">Release gate: 25 unit tests, 105 cross-browser checks, zero dependency vulnerabilities, and a validated 121-item UI audit.</p></section>
    <section className="section-shell decision-section" aria-labelledby="carryover-decisions"><header className="section-heading"><p className="eyebrow">Selected decisions</p><h2 id="carryover-decisions">The interface follows the responsibility model.</h2></header><div className="decision-grid">{CARRYOVER.decisions.map((decision, index) => <article key={decision.title}><span>0{index + 1}</span><h3>{decision.title}</h3><p>{decision.body}</p></article>)}</div></section>
    <section className="section-shell carryover-screens" aria-labelledby="carryover-screens"><header className="section-heading split-heading"><div><p className="eyebrow">Responsive evidence</p><h2 id="carryover-screens">Dense on desktop. Direct on mobile.</h2></div><p>Desktop pairs context and action. Mobile removes the control-room density and restores a strict record-first reading order.</p></header><div className="carryover-screen-grid"><figure><img src="/projects/carryover-handoff.png" alt="Carryover outgoing preparation and incoming cross-check ledger on desktop" width="1440" height="900"/><figcaption><strong>Two-way transfer</strong><span>Outgoing context and incoming responsibility remain distinct.</span></figcaption></figure><figure className="carryover-mobile-shot"><img src="/projects/carryover-mobile.png" alt="Carryover issue record on a narrow mobile screen" width="390" height="844"/><figcaption><strong>Mobile operating record</strong><span>No compressed desktop table or hidden status.</span></figcaption></figure></div></section>
    <section className="section-shell reflection-section" aria-labelledby="carryover-reflection"><div><p className="eyebrow">Reflection</p><h2 id="carryover-reflection">A credible prototype says what remains unproven.</h2></div><div><p>{CARRYOVER.reflection}</p><p className="disclosure">{CARRYOVER.disclosure}</p></div></section>
    <footer className="section-shell case-actions"><p className="eyebrow">Explore the work</p><h2>Follow one condition through the complete transfer.</h2><div className="button-row"><a className="button button-primary" href={`${CARRYOVER.liveUrl}/?tour=handoff`} target="_blank" rel="noreferrer">Run the handoff ↗</a><a className="button button-secondary" href={CARRYOVER.liveUrl} target="_blank" rel="noreferrer">Open Carryover ↗</a><a className="text-link" href={CARRYOVER.repoUrl} target="_blank" rel="noreferrer">View source ↗</a></div></footer>
  </article>;
}
