import { MERIDIAN } from "../data/portfolio";

const systemNodes = [
  ["Public narrative", "Thesis pages explain what Meridian believes and why."],
  ["Canonical portfolio", "Twenty-four typed records keep capital and company claims aligned."],
  ["Operating console", "Five workspaces turn the same record into attention, review, and reporting workflows."],
] as const;

export default function MeridianPage() {
  return <article className="case-study">
    <header className="case-hero section-shell"><div className="case-kicker"><span>Selected work / 01</span><span>Independent case study / {MERIDIAN.year}</span></div><h1>Meridian turns an investment thesis into an operating record.</h1><p>{MERIDIAN.problem}</p><div className="button-row"><a className="button button-primary" href={MERIDIAN.liveUrl} target="_blank" rel="noreferrer">Open Meridian ↗</a><a className="button button-secondary" href={`${MERIDIAN.liveUrl}/console`} target="_blank" rel="noreferrer">Open the console ↗</a><a className="text-link" href={MERIDIAN.repoUrl} target="_blank" rel="noreferrer">View source ↗</a></div></header>
    <section className="case-snapshot section-shell" aria-label="Project snapshot"><div><span>Role</span><strong>{MERIDIAN.responsibilities.join(" · ")}</strong></div><div><span>Stack</span><strong>{MERIDIAN.technologies.join(" · ")}</strong></div><div><span>Boundary</span><strong>Fictional product and data; client-side demonstration workspace</strong></div></section>
    <section className="section-shell case-problem" aria-labelledby="problem-title"><div><p className="eyebrow">The problem</p><h2 id="problem-title">Credibility had to survive a change in context.</h2></div><div className="long-copy"><p>A polished public site can explain what a firm believes. It cannot prove the firm knows what requires attention after the investment. A dense console can show the record, but without a coherent public narrative it feels like an isolated dashboard.</p><p>The challenge was to make both surfaces feel authored by the same institution while letting each solve a different job completely.</p></div></section>
    <section className="section-shell system-section" aria-labelledby="system-title"><header className="section-heading"><p className="eyebrow">System map</p><h2 id="system-title">Story becomes record. Record becomes decision.</h2></header><div className="system-map">{systemNodes.map(([title, body], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="section-shell evidence-section" aria-labelledby="evidence-title"><header className="section-heading"><p className="eyebrow">Engineering evidence</p><h2 id="evidence-title">The scope is visible in the product.</h2></header><div className="evidence-grid">{MERIDIAN.evidence.map((item) => <article key={item.label}><strong>{item.value}</strong><span>{item.label}</span><p>{item.detail}</p></article>)}</div><p className="evidence-note">Verification: 46 tests across ten files and the production TypeScript/Vite build passed on August 13, 2026.</p></section>
    <section className="section-shell decision-section" aria-labelledby="decision-title"><header className="section-heading"><p className="eyebrow">Selected decisions</p><h2 id="decision-title">The interface follows the operating logic.</h2></header><div className="decision-grid">{MERIDIAN.decisions.map((decision, index) => <article key={decision.title}><span>0{index + 1}</span><h3>{decision.title}</h3><p>{decision.body}</p></article>)}</div></section>
    <section className="section-shell screen-study" aria-labelledby="screens-title"><header className="section-heading split-heading"><div><p className="eyebrow">Responsive evidence</p><h2 id="screens-title">Same record. Different reading behavior.</h2></div><p>Desktop preserves comparison. Tablet reduces simultaneous demands. Mobile turns wide ledgers into direct company records.</p></header><figure className="desktop-screen"><img src="/projects/meridian-public.png" alt="Meridian public website on desktop" width="1440" height="900" /><figcaption><strong>Public narrative</strong><span>Page-specific composition, consistent institutional grammar.</span></figcaption></figure><div className="screen-pair"><figure><img src="/projects/meridian-overview.png" alt="Meridian console portfolio workspace on a laptop" width="1440" height="900" /><figcaption><strong>Operating console</strong><span>Attention and capital context before the full record.</span></figcaption></figure><figure className="mobile-screen"><img src="/projects/meridian-mobile.png" alt="Meridian responsive company record on mobile" width="390" height="844" /><figcaption><strong>Mobile record</strong><span>No compressed desktop table.</span></figcaption></figure></div></section>
    <section className="section-shell reflection-section" aria-labelledby="reflection-title"><div><p className="eyebrow">Reflection</p><h2 id="reflection-title">A strong demo should make its boundary clear.</h2></div><div><p>{MERIDIAN.reflection}</p><p className="disclosure">{MERIDIAN.disclosure}</p></div></section>
    <footer className="section-shell case-actions"><p className="eyebrow">Explore the work</p><h2>From institutional story to partner decision.</h2><div className="button-row"><a className="button button-primary" href={MERIDIAN.liveUrl} target="_blank" rel="noreferrer">Open Meridian ↗</a><a className="button button-secondary" href={`${MERIDIAN.liveUrl}/console`} target="_blank" rel="noreferrer">Open the console ↗</a><a className="text-link" href={MERIDIAN.repoUrl} target="_blank" rel="noreferrer">View source ↗</a></div></footer>
  </article>;
}
